/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  config: () => config2,
  default: () => Obsidisaurus,
  logger: () => logger
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/markdownProcessor.ts
var readline = __toESM(require("readline"));
var stream = __toESM(require("stream"));

// config.ts
var config;
function setSettings(settings) {
  config = settings;
}

// src/markdownProcessor.ts
async function processMarkdown(processedFileName, sourceContent, assetJson) {
  const sourceStream = new stream.Readable();
  sourceStream.push(sourceContent);
  sourceStream.push(null);
  const rl = readline.createInterface({
    input: sourceStream,
    output: process.stdout,
    terminal: false
  });
  let transformedContent = "";
  let inAdmonition = false, inQuote = false, inBlockComment = false;
  let admonition = { type: "", title: "", whitespaces: 0 };
  for await (const line of rl) {
    if (inBlockComment) {
      if (line.includes("%%")) inBlockComment = false;
      continue;
    }
    if (line.trim() === "%%") {
      inBlockComment = true;
      continue;
    }
    const withoutInlineComments = line.replace(/%%.*?%%/g, "").trimEnd();
    if (withoutInlineComments === "" && line.includes("%%")) continue;
    let processedLine = convertObsidianLinks(withoutInlineComments);
    processedLine = checkForAssets(processedLine, processedFileName, assetJson);
    processedLine = checkForLinks(processedLine);
    processedLine = convertHighlighting(processedLine);
    [processedLine, inAdmonition, inQuote, admonition] = convertAdmonition(processedLine, inAdmonition, inQuote, admonition);
    transformedContent += processedLine + "\n";
  }
  return transformedContent;
}
function convertObsidianLinks(line) {
  const pattern = new RegExp(`!\\[\\[(${config.docusaurusAssetSubfolderName}/.*?)\\]\\]`);
  const match = line.match(pattern);
  if (match !== null) {
    const newPath = `![](${match[1]})`;
    return line.replace(match[0], newPath);
  } else {
    return line;
  }
}
var parseAdmonitionData = (line) => {
  var _a, _b, _c;
  const match = line.match(/^>\s*\[!(?<type>.*)](?<title>.*)?/);
  if (!match) return { type: "", title: "", whitespaces: 0 };
  return {
    type: ((_a = match.groups) == null ? void 0 : _a.type) || "",
    title: ((_c = (_b = match.groups) == null ? void 0 : _b.title) == null ? void 0 : _c.trim()) || "",
    whitespaces: line.indexOf("[") - line.indexOf(">")
  };
};
var convertAdmonition = (line, isInAdmonition, isInQuote, admonition) => {
  if (!isInAdmonition && !isInQuote) {
    admonition = parseAdmonitionData(line);
  }
  if (isInAdmonition) {
    if (line.trim() === "") {
      line = ":::\n";
      isInAdmonition = false;
    } else {
      line = line.slice(admonition.whitespaces);
    }
  } else if (isInQuote) {
    if (line.trim() === "") {
      line = ">\n> \u2014 " + admonition.title + "\n";
      isInQuote = false;
    }
  } else if (admonition.type) {
    if (admonition.type.toLowerCase() === "quote") {
      line = "";
      isInQuote = true;
    } else {
      isInAdmonition = true;
      line = ":::" + admonition.type.toLowerCase();
      if (admonition.title) {
        line += "[" + admonition.title + "]";
      }
      line += "\n";
    }
  }
  return [line, isInAdmonition, isInQuote, admonition];
};
function convertHighlighting(line) {
  const converted = line.replace(/==(.+?)==/g, "<mark>$1</mark>");
  if (converted.startsWith("<mark>")) {
    return `{''}` + converted;
  }
  return converted;
}
function checkForLinks(line) {
  const pattern = /(?<!!)\[([^\]]+)\]\(([^)]+)\)/;
  const match = line.match(pattern);
  if (match) {
    const url = match[2];
    if (url.includes("http")) {
      return line;
    } else {
      const urlParts = url.split("/");
      if (urlParts.length <= 1) return line;
      let mainFolder = urlParts[0];
      const isBlog = isBlogFolder(mainFolder);
      if (isBlog) {
        mainFolder = removeBlogSuffix(mainFolder);
        urlParts[0] = mainFolder;
      }
      const processedUrlParts = processUrlParts(urlParts, isBlog);
      const newUrl = "/" + processedUrlParts.join("/");
      return line.replace(url, newUrl);
    }
  }
  return line;
}
function processUrlParts(urlParts, isBlog) {
  urlParts = [...urlParts];
  const [file, anchor] = urlParts[urlParts.length - 1].split("#");
  let parentFolder = urlParts[urlParts.length - 2];
  if (parentFolder.endsWith("+")) {
    parentFolder = parentFolder.replace("+", "");
    urlParts.pop();
    urlParts[urlParts.length - 1] = isBlog ? parentFolder.split("-").join("/") : removeNumberPrefix(parentFolder);
  } else if (file.endsWith(".md")) {
    urlParts[urlParts.length - 1] = file.replace(".md", "");
  }
  if (isBlog) {
    urlParts[urlParts.length - 1] = urlParts[urlParts.length - 1].split("-").join("/");
  }
  if (!isBlog) {
    urlParts = urlParts.map((part) => removeNumberPrefix(part));
  }
  if (anchor) {
    urlParts[urlParts.length - 1] = urlParts[urlParts.length - 1] + "#" + anchor.split("%20").join("-").toLowerCase();
  }
  return urlParts;
}
function isBlogFolder(mainFolder) {
  return mainFolder === "blog" || mainFolder.endsWith("__blog");
}
function removeBlogSuffix(mainFolder) {
  return mainFolder.replace("__blog", "");
}
function removeNumberPrefix(str) {
  return str.replace(/^\d+[.\-)\s%20]*\s*/, "").trim();
}
function getOrCreateSize(sizes, size, processedFileName) {
  let existingSize = sizes.find((s) => s.size === size);
  if (!existingSize) {
    existingSize = {
      size,
      inDocuments: [processedFileName],
      newName: []
    };
    sizes.push(existingSize);
  } else if (!existingSize.inDocuments.includes(processedFileName)) {
    existingSize.inDocuments.push(processedFileName);
  }
  return existingSize;
}
function checkForAssets(line, processedFileName, assetJson) {
  var _a;
  const match = line.match(/!\[(?:\|(?<size>\d+(x\d+)?))?\]\((?<path>.*?)\)/);
  if (match && match.groups) {
    let { size, path: path7 } = match.groups;
    const fileNameWithExtension = (_a = path7.split("/").pop()) != null ? _a : "";
    let [fileName, fileExtension] = fileNameWithExtension.split(".");
    fileName = fileName.replace(/ /g, "_");
    fileName = fileName.replace(/%20/g, "_");
    if (!(size == null ? void 0 : size.trim())) {
      size = "standard";
    }
    let existingAsset = assetJson.find((item) => item.fileName === fileName);
    let existingSize;
    if (existingAsset) {
      existingSize = getOrCreateSize(existingAsset.sizes, size, processedFileName);
    } else {
      existingAsset = {
        fileName,
        //@ts-ignore
        originalFileName: fileNameWithExtension,
        fileExtension,
        dateModified: (/* @__PURE__ */ new Date()).toISOString(),
        sourcePathRelative: path7,
        sizes: []
      };
      existingSize = getOrCreateSize(existingAsset.sizes, size, processedFileName);
      assetJson.push(existingAsset);
    }
    if (["jpg", "png", "webp", "jpeg", "bmp", "gif", "svg", "excalidraw"].includes(fileExtension)) {
      line = processImage(line, fileName, fileExtension, size, existingSize);
    } else {
      line = processAsset(line, fileName, fileExtension);
    }
  }
  return line;
}
function processImage(line, fileName, fileExtension, size, sizeObject) {
  var _a;
  const sizeSuffix = size === "standard" ? "" : `_${size}`;
  const extensionFormatMap = {
    "gif": `/assets/${fileName}${sizeSuffix}.${fileExtension}`,
    "svg": `/assets/${fileName}${sizeSuffix}.${fileExtension}`,
    //"svg": `/assets/${fileName}${sizeSuffix}.light.svg#light`,
    "excalidraw": `/assets/${fileName}${sizeSuffix}.excalidraw.light.svg#light`
  };
  let newPath = `/assets/${fileName}${sizeSuffix}.${config.convertedImageType}`;
  if (extensionFormatMap[fileExtension]) {
    newPath = extensionFormatMap[fileExtension];
    line = `![${fileName}](${newPath})`;
    if (fileExtension === "excalidraw") {
      const darkPath = newPath.replace(".light.svg#light", ".dark.svg#dark");
      line += `
![${fileName}](${darkPath})`;
    }
  } else {
    line = `![${fileName}](${newPath})`;
  }
  const newName = (_a = newPath.split("/").pop()) == null ? void 0 : _a.split("#")[0];
  if (newName && !sizeObject.newName.includes(newName)) {
    sizeObject.newName.push(newName);
  }
  return line;
}
function processAsset(line, fileName, fileExtension) {
  line = `[Download ${fileName}.${fileExtension}](${config.docusaurusAssetSubfolderName}/${fileName}.${fileExtension})`;
  return line;
}

// src/mainProcessor.ts
var import_obsidian = require("obsidian");
var fs5 = __toESM(require("fs"));
var path5 = __toESM(require("path"));

// src/fileScanner.ts
var fs = __toESM(require("fs"));
var path = __toESM(require("path"));
function getMainfolders(folderPath) {
  const folders = [];
  const absoluteFolderPath = path.resolve(folderPath);
  if (config.debug) {
    logger.info("\u{1F4C1} Processing path: %s", absoluteFolderPath);
  }
  const objects = fs.readdirSync(absoluteFolderPath);
  if (config.debug) {
    logger.info("\u{1F4C2} Found files: %o", objects);
  }
  objects.forEach((object) => {
    const filePath = path.join(absoluteFolderPath, object);
    const stats = fs.statSync(filePath);
    if (stats.isDirectory()) {
      let type;
      if (object.endsWith("__blog")) {
        type = "blogMulti";
      } else if (object.includes("blog")) {
        type = "blog";
      } else if (object.includes("docs")) {
        type = "docs";
      } else if (object.includes(config.obsidianAssetSubfolderName)) {
        type = "assets";
      } else {
        type = "ignore";
      }
      if (type !== "ignore" && type !== void 0) {
        folders.push({ name: object, type, files: [] });
      }
      if (config.debug) {
        logger.info("\u{1F50D} File: %s, Type: %s", object, type);
      }
    }
  });
  if (config.debug) {
    logger.info("\u{1F4E4} Returning folders: %o", folders);
  }
  return folders;
}
function searchFilesInFolder(directory) {
  let results = [];
  const skipFiles = ".DS_Store";
  const files = fs.readdirSync(directory);
  files.forEach((file) => {
    if (skipFiles.includes(file)) {
      if (config.debug) {
        logger.info(`\u23ED\uFE0F Skipped ${file}`);
      }
      return;
    }
    const filePath = path.join(directory, file);
    const stat = fs.statSync(filePath);
    if (stat && stat.isDirectory()) {
      results = results.concat(searchFilesInFolder(filePath));
    } else {
      results.push(filePath);
    }
  });
  return results;
}
function processSingleFolder(folder, basePath) {
  const dirPath = path.join(basePath, folder.name);
  const files = searchFilesInFolder(dirPath);
  folder.files = files;
  if (config.debug) {
    logger.info(
      "\u{1F4C4} Vault Files for %s: %s",
      folder.name,
      JSON.stringify(files)
    );
  }
}

// src/fileInfoBuilder.ts
var fs2 = __toESM(require("fs"));
var path2 = __toESM(require("path"));
function sanitizeFileName(fileName) {
  var _a;
  const parsedPath = path2.parse(fileName);
  const fileExtension = parsedPath.ext;
  let fileNameClean = parsedPath.name;
  const languageMatch = fileNameClean.match(/__([a-z]{2})$/i);
  let language;
  if (languageMatch) {
    fileNameClean = fileNameClean.split("__")[0];
    language = languageMatch[1];
  } else {
    if (!((_a = config) == null ? void 0 : _a.mainLanguage)) {
      throw new Error("Main language not defined in the configuration");
    }
    language = config.mainLanguage;
  }
  return { fileNameClean: fileNameClean.trim(), fileExtension, language };
}
function getTargetPath(sourceFileInfo, basePath) {
  var _a;
  const { type, language, pathSourceRelative, mainFolder, parentFolder, fileExtension } = sourceFileInfo;
  if (!type || !language || !pathSourceRelative || !parentFolder || !fileExtension || !mainFolder) {
    logger.error("\u{1F6A8} Required properties missing on sourceFileInfo");
    throw new Error("Missing required properties on sourceFileInfo");
  }
  const isMainLanguage = language === config.mainLanguage;
  const mainPathDict = {
    docs: isMainLanguage ? "" : path2.join("i18n", language, "docusaurus-plugin-content-docs", "current"),
    blog: isMainLanguage ? "" : path2.join("i18n", language, "docusaurus-plugin-content-blog"),
    blogMulti: isMainLanguage || !mainFolder ? "" : path2.join("i18n", language, `docusaurus-plugin-content-blog-${mainFolder}`),
    assets: path2.join("static", config.docusaurusAssetSubfolderName)
  };
  const mainPath = (_a = mainPathDict[type]) != null ? _a : "";
  let finalPathSourceRelative = pathSourceRelative;
  if (parentFolder.endsWith("+")) {
    const pathParts = finalPathSourceRelative.split(path2.sep);
    pathParts.pop();
    if (!isMainLanguage) pathParts.shift();
    if (pathParts.length > 0) {
      let lastPart = pathParts[pathParts.length - 1];
      if (lastPart.endsWith("+")) {
        lastPart = lastPart.slice(0, -1);
        pathParts[pathParts.length - 1] = lastPart;
      }
      finalPathSourceRelative = pathParts.join(path2.sep) + fileExtension;
    }
  }
  finalPathSourceRelative = finalPathSourceRelative.replace(`__${language}`, "");
  if (finalPathSourceRelative.endsWith(".yml.md")) {
    finalPathSourceRelative = finalPathSourceRelative.replace(".yml.md", ".yml");
  } else if (finalPathSourceRelative.endsWith(".md") && (type === "docs" || type === "blog" || type === "blogMulti")) {
    finalPathSourceRelative = finalPathSourceRelative.replace(/\.md$/, ".mdx");
  }
  sourceFileInfo.pathTargetRelative = path2.join(mainPath, finalPathSourceRelative);
  sourceFileInfo.pathTargetAbsolute = path2.join(
    basePath,
    config.docusaurusWebsiteDirectory,
    sourceFileInfo.pathTargetRelative
  );
  return sourceFileInfo;
}
function getSourceFileInfo(basePath, folder, filePath, vaultPath) {
  filePath = path2.resolve(filePath);
  const stats = fs2.statSync(filePath);
  const fileName = path2.basename(filePath);
  const { fileNameClean, fileExtension, language } = sanitizeFileName(fileName);
  const pathSourceRelative = path2.relative(vaultPath, filePath);
  let sourceFileInfo = {
    fileName,
    fileNameClean,
    fileExtension,
    language,
    mainFolder: folder.name,
    parentFolder: path2.basename(path2.dirname(filePath)),
    pathSourceAbsolute: filePath,
    pathSourceRelative,
    dateModified: stats.mtime,
    size: stats.size,
    type: folder.type
  };
  return getTargetPath(sourceFileInfo, basePath);
}

// src/changeTracker.ts
var fs3 = __toESM(require("fs"));
var path3 = __toESM(require("path"));
async function initializeJsonFile(filePath, defaultContent = "[]") {
  try {
    return JSON.parse(await fs3.promises.readFile(filePath, "utf-8"));
  } catch (error) {
    if (error.code === "ENOENT") {
      await fs3.promises.writeFile(filePath, defaultContent);
    } else {
      console.error(`Error reading file: ${filePath}`, error);
    }
    return [];
  }
}
async function writeJsonToFile(filePath, content) {
  await fs3.promises.writeFile(filePath, JSON.stringify(content, null, 2));
  return JSON.parse(await fs3.promises.readFile(filePath, "utf-8"));
}
function compareSource(sourceJson, targetJson) {
  const filesToProcess = [];
  sourceJson.forEach((sourceFile, i) => {
    const matchingTargetFile = targetJson.find(
      (file) => file.pathSourceRelative === sourceFile.pathSourceRelative
    );
    if (!matchingTargetFile) {
      filesToProcess.push({ index: i, reason: "Does not exist in targetJson" });
    }
  });
  return filesToProcess;
}
function getFilesToDelete(allSourceFilesInfo, targetJson) {
  const filesToDelete = [];
  targetJson.forEach((targetFile, i) => {
    const matchingSourceFile = allSourceFilesInfo.find(
      (file) => file.pathSourceRelative === targetFile.pathSourceRelative
    );
    const targetDate = new Date(targetFile.dateModified);
    const sourceDate = (matchingSourceFile == null ? void 0 : matchingSourceFile.dateModified) ? new Date(matchingSourceFile.dateModified) : null;
    if (!matchingSourceFile) {
      filesToDelete.push({
        index: i,
        reason: "it does not exist in sourceJson",
        pathKey: targetFile.pathSourceRelative
      });
    } else if (sourceDate && targetDate.getTime() < sourceDate.getTime()) {
      filesToDelete.push({
        index: i,
        reason: `its last modification date ${targetDate.toISOString()} is older than the date in sourceJson ${sourceDate.toISOString()}`,
        pathKey: targetFile.pathSourceRelative
      });
    }
  });
  return filesToDelete;
}
async function checkFilesExistence(targetJson) {
  const existentFiles = await Promise.all(
    targetJson.map(async (fileInfo) => {
      try {
        await fs3.promises.access(fileInfo.pathTargetAbsolute);
        const stats = await fs3.promises.stat(fileInfo.pathTargetAbsolute);
        fileInfo.dateModifiedTarget = stats.mtime;
        fileInfo.sizeTarget = stats.size;
        return fileInfo;
      } catch (err) {
        if (err.code !== "ENOENT") throw err;
        return null;
      }
    })
  );
  return existentFiles.filter((f) => f !== null);
}
async function deleteFiles(filesToDelete, targetJson, basePath) {
  filesToDelete.sort((a, b) => b.index - a.index);
  for (const fileToDelete of filesToDelete) {
    const targetFile = targetJson[fileToDelete.index];
    try {
      await fs3.promises.unlink(targetFile.pathTargetAbsolute);
      await deleteParentDirectories(targetFile.pathTargetAbsolute);
      targetJson.splice(fileToDelete.index, 1);
    } catch (error) {
      if (error.code !== "ENOENT") {
        logger.error(`Failed to delete file ${targetFile.pathTargetRelative}: ${error}`);
        continue;
      }
      targetJson.splice(fileToDelete.index, 1);
    }
  }
}
async function ensureDirectoryExistence(filePath) {
  const dir = path3.dirname(filePath);
  if (!fs3.existsSync(dir)) {
    await fs3.promises.mkdir(dir, { recursive: true });
  }
}
async function deleteParentDirectories(filepath) {
  let dirPath = path3.dirname(filepath);
  while (dirPath !== path3.dirname(dirPath)) {
    try {
      await fs3.promises.rmdir(dirPath);
    } catch (error) {
      const err = error;
      if (err.code !== "ENOTEMPTY" && err.code !== "EEXIST" && err.code !== "EPERM") {
        logger.error(`Failed to delete directory ${dirPath}: ${error}`);
      }
      return;
    }
    dirPath = path3.dirname(dirPath);
  }
}

// src/assetProcessor.ts
var fs4 = __toESM(require("fs"));
var path4 = __toESM(require("path"));
var import_util = __toESM(require("util"));
var copyFile2 = import_util.default.promisify(fs4.copyFile);
var mkdir2 = import_util.default.promisify(fs4.mkdir);
async function removeAssetReferences(filesToDelete, assetJson, websitePath) {
  for (const fileToDelete of filesToDelete) {
    if (!fileToDelete.pathKey) {
      continue;
    }
    for (let assetIndex = assetJson.length - 1; assetIndex >= 0; assetIndex--) {
      const asset = assetJson[assetIndex];
      for (let sizeIndex = asset.sizes.length - 1; sizeIndex >= 0; sizeIndex--) {
        const size = asset.sizes[sizeIndex];
        const docIndex = size.inDocuments.indexOf(fileToDelete.pathKey);
        if (docIndex !== -1) {
          size.inDocuments.splice(docIndex, 1);
          if (config.debug) {
            logger.info(
              `\u{1F5D1} Removed filePath from inDocuments: ${fileToDelete.pathKey}`
            );
          }
          if (size.inDocuments.length === 0) {
            const assetToRemove = size.newName;
            await removeAssetFromTarget(
              assetToRemove,
              config.docusaurusAssetSubfolderName,
              websitePath
            );
            asset.sizes.splice(sizeIndex, 1);
            if (config.debug) {
              logger.info(
                `\u{1F525} Removed size from sizes: ${size.size}`
              );
            }
          }
        }
      }
      if (asset.sizes.length === 0) {
        assetJson.splice(assetIndex, 1);
        if (config.debug) {
          logger.info(
            `\u{1F4A5} Removed asset from assetJson: ${asset.fileName}`
          );
        }
      }
    }
  }
  return assetJson;
}
async function removeAssetFromTarget(assetToRemove, docusaurusAssetSubfolderName, websitePath) {
  for (const asset of assetToRemove) {
    const assetPath = path4.join(
      websitePath,
      "static",
      docusaurusAssetSubfolderName,
      asset
    );
    try {
      await fs4.promises.unlink(assetPath);
      if (config.debug) {
        logger.info(`\u{1F5D1} Removed asset: ${assetPath}`);
      }
    } catch (error) {
      if (config.debug) {
        logger.error(`\u274C Error removing asset: ${assetPath}`, error);
      }
    }
  }
}
function getAssetsToProcess(assetJson, websitePath) {
  const documents = [];
  for (const [assetIndex, asset] of assetJson.entries()) {
    for (const [sizeIndex, size] of asset.sizes.entries()) {
      for (const name of size.newName) {
        documents.push({ assetIndex, sizeIndex, path: name });
      }
    }
  }
  const assetsToProcess = documents.filter((document2) => {
    const fileExists = fs4.existsSync(
      path4.join(
        websitePath,
        "static",
        config.docusaurusAssetSubfolderName,
        document2.path
      )
    );
    if (!fileExists && config.debug) {
      logger.info(`File ${document2.path} does not exist.`);
    }
    return !fileExists;
  });
  return assetsToProcess;
}
function clearFileFromAssetJson(filePath, assetJson) {
  for (let i = assetJson.length - 1; i >= 0; i--) {
    const asset = assetJson[i];
    for (let j = asset.sizes.length - 1; j >= 0; j--) {
      const size = asset.sizes[j];
      const idx = size.inDocuments.indexOf(filePath);
      if (idx !== -1) {
        size.inDocuments.splice(idx, 1);
        if (size.inDocuments.length === 0) {
          asset.sizes.splice(j, 1);
        }
      }
    }
    if (asset.sizes.length === 0) {
      assetJson.splice(i, 1);
    }
  }
}
async function copyAssetFilesToTarget(vaultPathPath, websitePath, assetJson, assetsToProcess) {
  const docusaurusAssetFolderPath = path4.join(
    websitePath,
    "static",
    config.docusaurusAssetSubfolderName
  );
  await mkdir2(docusaurusAssetFolderPath, { recursive: true });
  for (const assetToProcess of assetsToProcess) {
    const asset = assetJson[assetToProcess.assetIndex];
    const size = asset.sizes[assetToProcess.sizeIndex];
    const originalFilePath = path4.join(
      vaultPathPath,
      config.obsidianAssetSubfolderName,
      asset.originalFileName
    ).replace(/%20/g, " ");
    if (!fs4.existsSync(originalFilePath)) {
      logger.warn(`Source asset not found, skipping: ${originalFilePath}`);
      continue;
    }
    for (const newName of size.newName) {
      const newFilePath = path4.join(docusaurusAssetFolderPath, newName);
      if (["jpg", "png", "webp", "jpeg", "bmp", "gif"].includes(
        asset.fileExtension
      )) {
        try {
          if (size.size === "standard" && asset.fileExtension === "gif") {
            fs4.copyFileSync(originalFilePath, newFilePath);
            if (config.debug) {
              logger.info(
                `Image copied from ${originalFilePath} to ${newFilePath}`
              );
            }
          } else {
            await resizeImage(
              originalFilePath,
              newFilePath,
              size.size
            );
            if (config.debug) {
              logger.info(
                `Image resized and copied from ${originalFilePath} to ${newFilePath}`
              );
            }
          }
        } catch (error) {
          if (config.debug) {
            logger.info(
              `Failed to resize image and copy from ${originalFilePath} to ${newFilePath}: ${error.message}`
            );
          }
        }
      } else if (asset.fileExtension == "svg") {
        await copySVG(originalFilePath, newFilePath);
      } else if ([asset.fileExtension].includes("excalidraw")) {
        await copyExcalidraw(originalFilePath, newFilePath);
      } else {
        try {
          await copyFile2(originalFilePath, newFilePath);
          if (config.debug) {
            logger.info(
              `File copied from ${originalFilePath} to ${newFilePath}`
            );
          }
        } catch (error) {
          if (config.debug) {
            logger.error(
              `Failed to copy file from ${originalFilePath} to ${newFilePath}: ${error.message}`
            );
          }
        }
      }
    }
  }
}
async function deleteUnusedFiles(json, websitePath) {
  const targetDirectories = ["blog", "i18n", "docs"];
  const blogSuffix = "__blog";
  let filesFound = [];
  function exploreDirectory(directory) {
    const entries = fs4.readdirSync(directory, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path4.join(directory, entry.name);
      if (entry.isDirectory()) {
        exploreDirectory(fullPath);
      } else if (entry.isFile()) {
        filesFound.push(fullPath);
      }
    }
  }
  targetDirectories.forEach((dir) => {
    const dirPath = path4.join(websitePath, dir);
    if (fs4.existsSync(dirPath)) {
      exploreDirectory(dirPath);
    }
  });
  const allDirectories = fs4.readdirSync(websitePath, { withFileTypes: true });
  const otherDirectories = allDirectories.filter(
    (dir) => dir.name.endsWith(blogSuffix)
  );
  otherDirectories.forEach((dir) => {
    const dirPath = path4.join(websitePath, dir.name);
    exploreDirectory(dirPath);
  });
  for (const file of filesFound) {
    const fileIsUsed = json.some((j) => j.pathTargetAbsolute === file);
    if (!fileIsUsed) {
      await fs4.promises.unlink(file);
      logger.debug(`Deleted unused file: ${file}`);
    }
  }
}
async function resizeImage(originalFilePath, newFilePath, size) {
  const imageBuffer = await fs4.promises.readFile(originalFilePath);
  const blob = new Blob([imageBuffer]);
  const url = URL.createObjectURL(blob);
  const img = await new Promise((resolve3, reject) => {
    const el = new Image();
    el.onload = () => resolve3(el);
    el.onerror = reject;
    el.src = url;
  });
  URL.revokeObjectURL(url);
  const maxWidth = parseInt(config.convertedImageMaxWidth);
  let width;
  let height;
  if (size === "standard") {
    width = Math.min(img.naturalWidth, maxWidth);
    height = Math.round(img.naturalHeight * (width / img.naturalWidth));
  } else {
    const dimensions = size.split("x");
    width = parseInt(dimensions[0]);
    height = dimensions.length > 1 ? parseInt(dimensions[1]) : Math.round(img.naturalHeight * (width / img.naturalWidth));
  }
  const canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Canvas 2D context unavailable");
  ctx.drawImage(img, 0, 0, width, height);
  const resultBlob = await new Promise(
    (resolve3, reject) => canvas.toBlob((b) => b ? resolve3(b) : reject(new Error("Canvas toBlob failed")), "image/webp", 0.85)
  );
  const buffer = Buffer.from(await resultBlob.arrayBuffer());
  await fs4.promises.writeFile(newFilePath, buffer);
}
async function copySVG(originalFilePath, newFilePath) {
  await copyFile2(originalFilePath, newFilePath);
}
async function copyExcalidraw(originalFilePath, newFilePath) {
  const filePath = originalFilePath.replace(".md", "");
  const newDarkFilePath = newFilePath.replace(".light", ".dark");
  const darkFilePath = filePath + ".dark.svg";
  await copyFile2(darkFilePath, newDarkFilePath);
  const lightFilePath = filePath + ".light.svg";
  await copyFile2(lightFilePath, newFilePath);
}

// src/mainProcessor.ts
async function previewChanges(basePath, vaultPath) {
  const mainFolders = getMainfolders(vaultPath);
  mainFolders.forEach((folder) => processSingleFolder(folder, vaultPath));
  const allInfo = mainFolders.flatMap(
    (folder) => folder.files.map(
      (file) => getSourceFileInfo(basePath, folder, file, vaultPath)
    )
  );
  const allSourceFilesInfo = allInfo.filter((info) => info.type !== "assets");
  let targetJson = await initializeJsonFile(
    path5.join(basePath, "allFilesInfo.json")
  );
  targetJson = await checkFilesExistence(targetJson);
  const filesToDelete = getFilesToDelete(allSourceFilesInfo, targetJson);
  const filesToProcess = compareSource(allSourceFilesInfo, targetJson);
  return {
    filesToProcess: filesToProcess.length,
    filesToDelete: filesToDelete.length
  };
}
async function obsidiosaurusProcess(basePath, vaultPath) {
  const websitePath = path5.join(basePath, config.docusaurusWebsiteDirectory);
  const mainFolders = getMainfolders(vaultPath);
  mainFolders.forEach((folder) => processSingleFolder(folder, vaultPath));
  if (config.debug) {
    logger.info(
      "\u{1F4C1} Folder structure with Files: %s",
      JSON.stringify(mainFolders)
    );
  }
  const allInfo = mainFolders.flatMap(
    (folder) => folder.files.map(
      (file) => getSourceFileInfo(basePath, folder, file, vaultPath)
    )
  );
  const allSourceFilesInfo = allInfo.filter(
    (info) => info.type !== "assets"
  );
  const allSourceAssetsInfo = allInfo.filter(
    (info) => info.type === "assets"
  );
  let targetJson = await initializeJsonFile(
    path5.join(basePath, "allFilesInfo.json")
  );
  let assetJson = await initializeJsonFile(
    path5.join(basePath, "assetInfo.json")
  );
  targetJson = await checkFilesExistence(targetJson);
  const filesToDelete = getFilesToDelete(
    allSourceFilesInfo,
    targetJson
  );
  await deleteFiles(filesToDelete, targetJson, basePath);
  await removeAssetReferences(filesToDelete, assetJson, websitePath);
  targetJson = await writeJsonToFile(
    path5.join(basePath, "allFilesInfo.json"),
    targetJson
  );
  await writeJsonToFile(
    path5.join(basePath, "allSourceAssetsInfo.json"),
    allSourceAssetsInfo
  );
  const filesToProcess = compareSource(allSourceFilesInfo, targetJson);
  if (filesToProcess.length > 0) {
    new import_obsidian.Notice(`Processing ${filesToProcess.length} files`);
    const filesToProcessIndices = filesToProcess.map((file) => file.index);
    const filesToMarkdownProcess = allSourceFilesInfo.filter(
      (_, index) => filesToProcessIndices.includes(index)
    );
    await copyMarkdownFilesToTarget(
      filesToMarkdownProcess,
      basePath,
      targetJson,
      assetJson
    );
    await writeJsonToFile(
      path5.join(basePath, "allFilesInfo.json"),
      targetJson
    );
  } else {
    new import_obsidian.Notice("Nothing to process");
  }
  const assetsToProcess = getAssetsToProcess(assetJson, websitePath);
  new import_obsidian.Notice(`Processing ${assetsToProcess.length} assets`);
  if (assetsToProcess.length > 0) {
    await copyAssetFilesToTarget(
      vaultPath,
      websitePath,
      assetJson,
      assetsToProcess
    );
  }
  await deleteUnusedFiles(targetJson, websitePath);
  logger.info("Obsidiosaurus run successfully");
  new import_obsidian.Notice("Obsidiosaurus run successfully");
  return true;
}
async function copyMarkdownFilesToTarget(files, basePath, targetJson, assetJson) {
  const results = [];
  const promises5 = files.map(async (file) => {
    const { pathTargetAbsolute, pathSourceAbsolute, pathSourceRelative } = file;
    if (pathTargetAbsolute && pathSourceAbsolute && pathSourceRelative) {
      await ensureDirectoryExistence(pathTargetAbsolute);
      const sourceContent = await fs5.promises.readFile(
        pathSourceAbsolute,
        "utf-8"
      );
      clearFileFromAssetJson(pathSourceRelative, assetJson);
      const transformedContent = await processMarkdown(
        pathSourceRelative,
        sourceContent,
        assetJson
      );
      if (transformedContent) {
        await fs5.promises.writeFile(
          pathTargetAbsolute,
          String(transformedContent)
        );
      }
      if (config.debug) {
        logger.info(
          `\u{1F4E4} Converted file from ${pathSourceAbsolute} to ${pathTargetAbsolute}`
        );
      }
    }
    results.push(file);
  });
  await Promise.all(promises5);
  targetJson.push(...results);
  await fs5.promises.writeFile(
    path5.join(basePath, "assetInfo.json"),
    JSON.stringify(assetJson, null, 2)
  );
}

// main.ts
var import_path = __toESM(require("path"));
var fs6 = __toESM(require("fs"));
var STATUS_DIR = ".obsidiosaurus";
var STATUS_FILE = "last-run.json";
async function writeStatus(vaultPath, status) {
  try {
    const dir = import_path.default.join(vaultPath, STATUS_DIR);
    await fs6.promises.mkdir(dir, { recursive: true });
    await fs6.promises.writeFile(
      import_path.default.join(dir, STATUS_FILE),
      JSON.stringify(status, null, 2)
    );
  } catch (err) {
    logger.error(`Failed to write obsidiosaurus status file: ${err}`);
  }
}
var logger = console;
var config2 = {
  obsidianVaultDirectory: "./vault",
  docusaurusWebsiteDirectory: "./website",
  obsidianAssetSubfolderName: "assets",
  docusaurusAssetSubfolderName: "assets",
  mainLanguage: "en",
  convertedImageType: "webp",
  convertedImageMaxWidth: "2500",
  debug: false,
  developer: false
};
var Obsidisaurus = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    if (this.settings.debug) {
      logger.info("\u{1F7E2} Obsidiosaurus Plugin loaded");
    }
    const ribbonIconEl = this.addRibbonIcon("file-up", "Obsidiosaurus", async () => {
      await this.runBuild({ skipConfirm: false });
    });
    ribbonIconEl.addClass("my-plugin-ribbon-class");
    this.addCommand({
      id: "run",
      name: "Run Obsidiosaurus",
      callback: async () => {
        await this.runBuild({ skipConfirm: true });
      }
    });
    this.addCommand({
      id: "run-with-confirm",
      name: "Run Obsidiosaurus (preview changes first)",
      callback: async () => {
        await this.runBuild({ skipConfirm: false });
      }
    });
    this.addSettingTab(new SettingTab(this.app, this));
  }
  async runBuild({ skipConfirm }) {
    try {
      if (!(this.app.vault.adapter instanceof import_obsidian2.FileSystemAdapter)) return;
      const vaultPath = this.app.vault.adapter.getBasePath();
      const basePath = import_path.default.dirname(vaultPath);
      const executeBuild = async (preview2) => {
        var _a;
        const startedAt = (/* @__PURE__ */ new Date()).toISOString();
        await writeStatus(vaultPath, {
          status: "running",
          startedAt,
          filesToProcess: preview2 == null ? void 0 : preview2.filesToProcess,
          filesToDelete: preview2 == null ? void 0 : preview2.filesToDelete,
          version: this.manifest.version
        });
        try {
          logger.info("Obsidiosaurus started");
          new import_obsidian2.Notice("Obsidiosaurus started");
          await obsidiosaurusProcess(basePath, vaultPath);
          await writeStatus(vaultPath, {
            status: "success",
            startedAt,
            finishedAt: (/* @__PURE__ */ new Date()).toISOString(),
            filesToProcess: preview2 == null ? void 0 : preview2.filesToProcess,
            filesToDelete: preview2 == null ? void 0 : preview2.filesToDelete,
            version: this.manifest.version
          });
        } catch (error) {
          if (this.settings.debug) {
            const errorMessage = `Obsidiosaurus crashed in function with the following error:
${error.stack}`;
            logger.error(errorMessage);
            new import_obsidian2.Notice(`Obsidiosaurus crashed. ${errorMessage}`);
          } else {
            logger.error(`Obsidiosaurus crashed with error message: 
${error} `);
            new import_obsidian2.Notice("Obsidiosaurus crashed. Check log files for more info");
          }
          await writeStatus(vaultPath, {
            status: "error",
            startedAt,
            finishedAt: (/* @__PURE__ */ new Date()).toISOString(),
            filesToProcess: preview2 == null ? void 0 : preview2.filesToProcess,
            filesToDelete: preview2 == null ? void 0 : preview2.filesToDelete,
            error: { message: String((_a = error == null ? void 0 : error.message) != null ? _a : error), stack: error == null ? void 0 : error.stack },
            version: this.manifest.version
          });
        }
      };
      const preview = await previewChanges(basePath, vaultPath);
      if (skipConfirm) {
        await executeBuild(preview);
        return;
      }
      new ConfirmModal(this.app, preview, () => executeBuild(preview)).open();
    } catch (error) {
      logger.error(`Obsidiosaurus preview failed: 
${error}`);
      new import_obsidian2.Notice("Could not calculate changes. Check log files for more info");
    }
  }
  onunload() {
    if (config2.debug) {
      logger.info("\u26AA Obsidiosaurus Plugin unloaded");
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, config2, await this.loadData());
    setSettings(this.settings);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var SettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Directories").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Docusaurus directory").setDesc("Path to your Docusaurus instance").addText((text) => text.setPlaceholder("Enter paths").setValue(this.plugin.settings.docusaurusWebsiteDirectory).onChange(async (value) => {
      this.plugin.settings.docusaurusWebsiteDirectory = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Assets").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Obsidian asset folder").setDesc("Name of the Obsidian asset folder").addText((text) => text.setPlaceholder("Enter folders").setValue(this.plugin.settings.obsidianAssetSubfolderName).onChange(async (value) => {
      this.plugin.settings.obsidianAssetSubfolderName = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Docusaurus asset folder").setDesc("Name of the Docusaurus asset folder").addText((text) => text.setPlaceholder("Enter folders").setValue(this.plugin.settings.docusaurusAssetSubfolderName).onChange(async (value) => {
      this.plugin.settings.docusaurusAssetSubfolderName = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Image type").setDesc("Format in which to convert all images").addDropdown((dropdown) => dropdown.addOptions({
      "webp": "WebP"
    }).setValue(this.plugin.settings.convertedImageType).onChange(async (value) => {
      this.plugin.settings.convertedImageType = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Image width").setDesc("Set the max width for the images in [px]").addText((number) => number.setPlaceholder("2500").setValue(this.plugin.settings.convertedImageMaxWidth).onChange(async (value) => {
      this.plugin.settings.convertedImageMaxWidth = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Language").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Main language").setDesc("Your main language code to publish").addText((text) => text.setPlaceholder("Enter language code").setValue(this.plugin.settings.mainLanguage).onChange(async (value) => {
      this.plugin.settings.mainLanguage = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Developer").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Debug mode").setDesc("Better logging for debugging").addToggle((value) => {
      value.setValue(this.plugin.settings.debug).onChange((value2) => {
        this.plugin.settings.debug = value2;
        void this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Developer mode").setDesc("Only for plugin developers").addToggle((value) => {
      value.setValue(this.plugin.settings.debug).onChange((value2) => {
        this.plugin.settings.debug = value2;
        void this.plugin.saveSettings();
      });
    });
  }
};
var ConfirmModal = class extends import_obsidian2.Modal {
  constructor(app, preview, onConfirm) {
    super(app);
    this.preview = preview;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Run Obsidiosaurus?" });
    const { filesToProcess, filesToDelete } = this.preview;
    if (filesToProcess === 0 && filesToDelete === 0) {
      contentEl.createEl("p", { text: "Nothing to do \u2014 all files are up to date." });
    } else {
      const list = contentEl.createEl("ul");
      if (filesToProcess > 0)
        list.createEl("li", { text: `${filesToProcess} file${filesToProcess !== 1 ? "s" : ""} will be converted / updated` });
      if (filesToDelete > 0)
        list.createEl("li", { text: `${filesToDelete} file${filesToDelete !== 1 ? "s" : ""} will be deleted from website` });
    }
    const buttonRow = contentEl.createDiv({ cls: "modal-button-container" });
    buttonRow.createEl("button", { text: "Cancel" }).addEventListener("click", () => {
      this.close();
    });
    const confirmBtn = buttonRow.createEl("button", {
      text: filesToProcess === 0 && filesToDelete === 0 ? "OK" : "Run",
      cls: "mod-cta"
    });
    confirmBtn.addEventListener("click", () => {
      this.close();
      if (filesToProcess > 0 || filesToDelete > 0) {
        void this.onConfirm();
      }
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
